### ISSUE TITLE
TypeError: 'IPv4Address' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by incognico** [sqproxy/sqredirect#2]
After some pyton upgrade woes (now v3.10), I get the fllowing error:

```
Dec 23 18:40:11 twlz sqproxy[2022]: 2021-12-23 18:40:11,171 [INFO] [main] Building eBPF program ..., cflags=['-include', 'utils.h', '-DUSE_IPPORT_KEY']
Dec 23 18:40:14 twlz sqproxy[2022]: Traceback (most recent call last):
Dec 23 18:40:14 twlz sqproxy[2022]:   File "/usr/bin/sqredirect", line 8, in <module>
Dec 23 18:40:14 twlz sqproxy[2022]:     sys.exit(sqredirect())
Dec 23 18:40:14 twlz sqproxy[2022]:   File "/usr/lib/python3.10/site-packages/sqredirect/redirect.py", line 342, in sqredirect
Dec 23 18:40:14 twlz sqproxy[2022]:     main(args.ports, args.interface)
Dec 23 18:40:14 twlz sqproxy[2022]:   File "/usr/lib/python3.10/site-packages/sqredirect/redirect.py", line 163, in main
Dec 23 18:40:14 twlz sqproxy[2022]:     addr_gameserver2proxy_port[AddrKey(ip, game_port)] = c_uint16(proxy_port)
Dec 23 18:40:14 twlz sqproxy[2022]: TypeError: 'IPv4Address' object cannot be interpreted as an integer
Dec 23 18:40:14 twlz sqproxy[2011]: 2021-12-23 18:40:14,739 [ERROR] [source_query_proxy.epbf] eBPF redirection exit with code None
```

**Comment by spumer** [comment]
Yea, it's removed in Python 3.10

Py 3.8 says:
```
<stdin>:1: DeprecationWarning: an integer is required (got type IPv4Address).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
c_uint(0)
```

https://docs.python.org/release/3.10.0/whatsnew/changelog.html#python-3-10-0-final

```
bpo-41974: Removed special methods __int__, __float__, __floordiv__, __mod__, __divmod__, __rfloordiv__, __rmod__ and __rdivmod__ of the complex class. They always raised a TypeError.
```

**Comment by spumer** [comment]
Version 1.2.2 relesead
